# Generated by Django 4.2.6 on 2024-01-25 22:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+201234567890'. Up to 13 digits allowed and only E.G phone accept.", regex='^\\+?201\\d{8,11}$')]),
        ),
    ]
