# Generated by Django 4.2.6 on 2024-01-30 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_profile_profileimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ProfileImg',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
