# Generated by Django 4.2.6 on 2024-02-12 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='unconfirmed_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
