# Generated by Django 4.2.6 on 2024-02-14 13:47

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_profile_profileimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ProfileImg',
            field=models.ImageField(default='', upload_to=accounts.models.GetImageUploadTo),
        ),
    ]
