# Generated by Django 4.2.6 on 2024-02-15 09:46

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_profile_profileimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_company',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='ProfileImg',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.GetImageUploadTo),
        ),
    ]
