# Generated by Django 4.2.6 on 2024-02-15 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_profile_is_company_alter_profile_profileimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_company',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
