# Generated by Django 4.2.6 on 2024-02-17 08:16

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_profile_is_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to=accounts.models.GetfileUploadTo),
        ),
    ]
