# Generated by Django 4.2.6 on 2024-02-17 09:38

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_profile_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cv',
            field=models.FileField(blank=True, default='', null=True, upload_to=accounts.models.GetfileUploadTo),
        ),
    ]
