# Generated by Django 4.2.6 on 2024-02-17 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_profile_job_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='job_title',
            new_name='specialization',
        ),
    ]
