# Generated by Django 4.2.6 on 2024-02-17 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_rename_job_title_profile_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_company',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
