# Generated by Django 4.2.6 on 2024-02-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_alter_profile_is_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_cv_public',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_company',
            field=models.BooleanField(default=True),
        ),
    ]
