# Generated by Django 4.2.6 on 2024-02-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_alter_profile_is_cv_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_cv_public',
            field=models.BooleanField(),
        ),
    ]
