# Generated by Django 4.2.6 on 2024-02-17 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='cv',
            field=models.FileField(blank=True, default='', null=True, upload_to=''),
        ),
    ]
